# Generated by Django 2.0.7 on 2018-07-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=100)),
                ('location', models.CharField(choices=[('silicon_valley', 'Silicon Valley, CA'), ('seattle', 'Seattle, WA'), ('los_angeles', 'Los Angeles, CA'), ('dallas', 'Dallas, TX'), ('chicago', 'Chicago, IL'), ('tulsa', 'Tulsa, OK'), ('tysons_corner', 'Tysons Corner, VA'), ('east_bay', 'East Bay, CA'), ('online', 'Online')], default='silicon_valley', max_length=14)),
                ('favorite_language', models.CharField(choices=[('python', 'Python'), ('ruby', 'Ruby'), ('javascript', 'JavaScript')], default='python', max_length=10)),
                ('comment', models.CharField(max_length=250)),
            ],
        ),
    ]
